version: "2"

run:
  timeout: 5m
  tests: false
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - unconvert
  disable:
    - gosec  # Temporarily disabled due to false positives with RGBA conversions
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: increment-decrement
        - name: var-naming
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: indent-error-flow
    
    gosec:
      config:
        G115: "0"  # Disable integer overflow conversion warnings
        G304: "0"  # Disable file inclusion warnings
        G306: "0"  # Disable file permission warnings

formatters:
  enable:
    - gofmt
    - goimports
