run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gosec
    - unconvert

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: indent-error-flow
  
  gosec:
    excludes:
      - G304 # File path provided as input
      - G306 # Poor file permissions

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
  
  max-issues-per-linter: 0
  max-same-issues: 0
