# GoReleaser configuration
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: converttifpdf
    main: ./cmd/converttifpdf
    binary: converttifpdf
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target x86_64-linux-gnu
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

  - id: converttifpdf-windows
    main: ./cmd/converttifpdf
    binary: converttifpdf
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target x86_64-windows-gnu
      - CXX=zig c++ -target x86_64-windows-gnu
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Refactors'
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: 'Other Changes'
      order: 999

release:
  github:
    owner: dhushon
    name: go-tifpdf2png
  name_template: "{{.ProjectName}} {{.Version}}"
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## TIFF/PDF to PNG Converter Release {{.Version}}
    
    This release includes pre-built binaries for:
    - **Linux** (x86_64 amd64) - with full PDF support via CGO
    - **Windows** (x86_64 amd64) - with full PDF support via CGO
    
    **macOS Users:** Install via Go to compile with CGO for full PDF support:
    ```bash
    go install github.com/dhushon/go-tifpdf2png/cmd/converttifpdf@{{.Tag}}
    ```
    This compiles natively on your Mac with full TIFF and PDF support.
    
    ### Installation
    
    Download the appropriate archive for your platform from the assets below, extract it, and place the `converttifpdf` binary in your PATH.
  footer: |
    ---
    **Full Changelog**: https://github.com/dhushon/go-tifpdf2png/compare/{{.PreviousTag}}...{{.Tag}}

# Generate Software Bill of Materials
sboms:
  - artifacts: archive

# Announce releases (optional - requires additional configuration)
# announce:
#
